import { FhevmType } from "@fhevm/hardhat-plugin";
import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";
import fs from "node:fs";
import path from "node:path";

function normalizePath(p: string) {
  return p.replaceAll("\\", "/");
}

task("task:miner:address", "Prints the MinerNFT and ConfidentialGold addresses").setAction(
  async function (_taskArguments: TaskArguments, hre) {
    const { deployments } = hre;

    const miner = await deployments.get("MinerNFT");
    const gold = await deployments.get("ConfidentialGold");

    console.log(`MinerNFT        : ${miner.address}`);
    console.log(`ConfidentialGold: ${gold.address}`);
  },
);

task("task:miner:mint", "Mints exactly one Miner NFT for the caller").setAction(async function (_args: TaskArguments, hre) {
  const { ethers, deployments } = hre;

  const miner = await deployments.get("MinerNFT");
  const minerContract = await ethers.getContractAt("MinerNFT", miner.address);
  const [signer] = await ethers.getSigners();

  const tx = await minerContract.connect(signer).mintMiner();
  console.log(`Wait for tx:${tx.hash}...`);
  const receipt = await tx.wait();
  console.log(`tx:${tx.hash} status=${receipt?.status}`);

  const tokenId = await minerContract.minerTokenId(signer.address);
  console.log(`Miner tokenId: ${tokenId}`);
});

task("task:miner:decrypt-power", "Decrypts the miner power for a given tokenId")
  .addParam("tokenid", "Miner tokenId")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { ethers, deployments, fhevm } = hre;

    await fhevm.initializeCLIApi();

    const tokenId = BigInt(taskArguments.tokenid);
    const miner = await deployments.get("MinerNFT");
    const minerContract = await ethers.getContractAt("MinerNFT", miner.address);
    const [signer] = await ethers.getSigners();

    const encryptedPower = await minerContract.minerPower(tokenId);
    const power = await fhevm.userDecryptEuint(FhevmType.euint16, encryptedPower, miner.address, signer);
    console.log(`tokenId=${tokenId} power=${power}`);
  });

task("task:miner:mine", "Mines Gold using a Miner NFT once per 24 hours")
  .addParam("tokenid", "Miner tokenId")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { ethers, deployments } = hre;

    const tokenId = BigInt(taskArguments.tokenid);
    const miner = await deployments.get("MinerNFT");
    const minerContract = await ethers.getContractAt("MinerNFT", miner.address);
    const [signer] = await ethers.getSigners();

    const tx = await minerContract.connect(signer).mine(tokenId);
    console.log(`Wait for tx:${tx.hash}...`);
    const receipt = await tx.wait();
    console.log(`tx:${tx.hash} status=${receipt?.status}`);
  });

task("task:gold:decrypt-balance", "Decrypts ConfidentialGold balance for an address")
  .addOptionalParam("user", "User address (defaults to signer[0])")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { ethers, deployments, fhevm } = hre;

    await fhevm.initializeCLIApi();

    const gold = await deployments.get("ConfidentialGold");
    const goldContract = await ethers.getContractAt("ConfidentialGold", gold.address);
    const [signer] = await ethers.getSigners();

    const user = taskArguments.user ?? signer.address;
    const encryptedBalance = await goldContract.confidentialBalanceOf(user);
    if (encryptedBalance === ethers.ZeroHash) {
      console.log(`user=${user} balance=0`);
      return;
    }

    if (user.toLowerCase() !== signer.address.toLowerCase()) {
      console.log(`user=${user} encryptedBalance=${encryptedBalance}`);
      console.log(`Cannot decrypt another user's balance with signer=${signer.address}`);
      return;
    }

    const balance = await fhevm.userDecryptEuint(FhevmType.euint64, encryptedBalance, gold.address, signer);
    console.log(`user=${user} balance=${balance}`);
  });

task("task:sync-frontend", "Generates home/src/config/contracts.ts from deployments")
  .addOptionalParam("out", "Output file path", "home/src/config/contracts.ts")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { deployments, network } = hre;
    const outFile = path.resolve(process.cwd(), taskArguments.out);

    const miner = await deployments.get("MinerNFT");
    const gold = await deployments.get("ConfidentialGold");

    const content =
      `// Auto-generated by 'npx hardhat task:sync-frontend --network ${network.name}'\n` +
      `// Do not edit manually.\n\n` +
      `export const CHAIN_ID = ${network.config.chainId ?? 0} as const;\n\n` +
      `export const MINER_NFT_ADDRESS = ${JSON.stringify(miner.address)} as const;\n` +
      `export const CONFIDENTIAL_GOLD_ADDRESS = ${JSON.stringify(gold.address)} as const;\n\n` +
      `export const MINER_NFT_ABI = ${JSON.stringify(miner.abi, null, 2)} as const;\n\n` +
      `export const CONFIDENTIAL_GOLD_ABI = ${JSON.stringify(gold.abi, null, 2)} as const;\n`;

    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, content, "utf8");

    console.log(`Wrote ${normalizePath(path.relative(process.cwd(), outFile))}`);
  });
